# Generated by Django 5.1.1 on 2024-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='if user dont have access to this course can they see this '),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('draft', 'draft'), ('soon', 'coming soon')], default='pub', max_length=10),
        ),
    ]
